exchange:
  api_key: fdXHFOyUxnZCd03RlKtAKU4wLztxy4F3MLid6BxiUsKPmmZr13kOoggJSwbfvjDT
  api_secret: 5nKTXcTpCjVQnpKI0M0hT1gCDbOvkJ53LRrCcC1D4qhYVOZ6QeZ90qKOcm3upUrZ
  exchange_id: binance
  max_retries: 5
  max_trades: 2
  pairs:
    ADA/USDC:
      max_position: 1000.0
      min_amount: 10.0
      min_cost: 10.0
      min_signal_confidence: 0.82
      min_volume_score: 0.7
      precision: 2
      price_precision: 4
      volatility_threshold: 0.03
    XRP/USDC:
      max_position: 1000.0
      min_amount: 10.0
      min_cost: 10.0
      min_signal_confidence: 0.82
      min_volume_score: 0.7
      precision: 2
      price_precision: 4
      volatility_threshold: 0.03
  position_loss_limit: 20.0
  recvWindow: 60000
  retry_delay: 3
  risk_amount: 15.0
  status_interval: 300
  stop_loss: 0.02
  take_profit: 0.015
  test_mode: false
  trailing_stop: 0.005
  update_interval: 2
risk:
  max_daily_loss: 50.0
  max_drawdown: 0.05
  max_position_risk: 0.01
  recovery_threshold: 0.02
  volatility_adjustment: true
scanner:
  counter_spoof:
    enabled: true
    lookback_periods: 10
    min_volume: 0.5
    threshold: 0.4
  dex_array:
    enabled: true
    levels: 3
    max_spread: 0.002
    min_volume: 0.5
    threshold: 0.166
  volume_filter:
    enabled: true
    min_24h_volume: 10000
    min_trades: 50
    min_volume_increase: 1.5
    volume_trend_periods: 12
system:
  balance_cache_time: 60
  log_backups: 10
  log_level: INFO
  market_data_timeout: 10
  max_log_size: 52428800
  max_threads: 4
  order_timeout: 30
  request_timeout: 30
